### ISSUE TITLE
🐛 [BUG] <问题标题>开机免输密码会造成小部件和部分应用不加载

### ISSUE THREAD

**Issue by u2shana** [Cemiuiler-Development-Team/Cemiuiler#113]
### 问题描述

开机免输密码会造成小部件和部分应用不加载
需要手动锁屏再输一次图形密码才会加载

如果无法解决的话建议在选项加个提示

### 模块日志

。。。。

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

小米

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

最新

**Comment by mu7220** [comment]
个人认为已经提示到位，出现相关问题不关cemiuiler的事

顺带一提，woobox for voyager 也是同样做法
