### ISSUE TITLE
作用域添加Gboard

### ISSUE THREAD

**Issue by Rbqwow** [Cemiuiler-Development-Team/Cemiuiler#132]
### 仓库地址

https://github.com/RC1844/MIUI_IME_Unlock

### 移植内容

解锁输入法全面屏优化 作用域并不会自动勾选Gboard 而原模块可以

**Comment by mu7220** [comment]
一开始是有添加的，后面去除了
Sevtinge 说只默认勾选几个小米自家输入法，剩下的自己勾

~~毕竟模块推荐作用域有点长~~
