### ISSUE TITLE
💡 [需求] <自定义/规范几个系统应用的存储位置>

### ISSUE THREAD

**Issue by wobenchunzhen** [Cemiuiler-Development-Team/Cemiuiler#142]
### 需求内容

**截屏**

截图保存到 Pictures/Screenshots

（来自模块 MIUI QOL，项目地址：https://github.com/Xposed-Modules-Repo/io.github.chsbuffer.miuihelper/releases/tag/16-1.1.14 ）

**屏幕录制**

录屏保存到 Movies/ScreenRecorder

（来自模块 MIUI QOL）

**下载管理程序**

自定义新建下载存储目录

### 实现思路&截图

![QQ图片20230527094613](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/62054486/38754f96-964a-4a7b-b78c-41342bcce066)
![QQ图片20230527094626](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/62054486/03130a3b-7054-4e6e-bd13-16673e1339f2)

### 简单例子

这样可以挽救一下 MIUI 及其不规范的系统应用存储位置设计

**Comment by mu7220** [comment]
差个下载管理，剩下两个好了，等下个版本（1.1.116-release）
