### ISSUE TITLE
💡 [需求] 桌面hook默认不修改大图标圆角

### ISSUE THREAD

**Issue by misaka-13766** [Cemiuiler-Development-Team/Cemiuiler#144]
### 需求内容

目前只要hook桌面就会将大图标变成圆角矩形，而修改图标圆角至99后即使中等图标会变回原状，然而2x2图标会从方形变成圆形，对部分应用图标而言影响显示效果。

### 简单例子

桌面hook后默认不修改圆角，桌面原来是什么样子就是什么样子，只有启动“中等图标圆角跟随”时才修改图标圆角。

**Comment by mu7220** [comment]
前面的修了，最后那个只有开启中等圆角跟随才修改大图标圆角，经考虑不做调整
