### ISSUE TITLE
🐛 [BUG] 网速指示器_双排显示

### ISSUE THREAD

**Issue by Adlyq** [Cemiuiler-Development-Team/Cemiuiler#148]
### 问题描述

网速指示器双排显示异常，不能双排显示，只显示上传网速

### 模块日志

----part 2 start----
[ 2023-05-29T18:53:33.368    10265: 21933: 21933 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:33.406    10265: 21933: 21933 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:33.751    10265: 21933: 21933 I/LSPosed-Bridge  ] Cemiuiler: packageName com.miui.weather2
[ 2023-05-29T18:53:33.751    10265: 21933: 21933 I/LSPosed-Bridge  ] Cemiuiler: Hook com.miui.weather2
[ 2023-05-29T18:53:33.752    10265: 21933: 21933 I/LSPosed-Bridge  ] Cemiuiler: SetDeviceLevel Start to hook package com.miui.weather2
[ 2023-05-29T18:53:33.769    10265: 21933: 21933 I/LSPosed-Bridge  ] Cemiuiler: SetDeviceLevel Hook Success!
[ 2023-05-29T18:53:33.771    10265: 21933: 21933 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:33.771    10265: 21933: 21933 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:35.664    10075: 32238: 32238 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:35.690    10075: 32238: 32238 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:35.927    10075: 32238: 32238 I/LSPosed-Bridge  ] Cemiuiler: packageName com.sevtinge.cemiuiler
[ 2023-05-29T18:53:36.040    10075: 32238: 22308 I/LSPosed-Bridge  ] Cemiuiler: packageName com.miui.contentcatcher
[ 2023-05-29T18:53:36.042    10075: 32238: 22308 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:36.042    10075: 32238: 22308 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:36.052    10075: 32238: 22308 I/LSPosed-Bridge  ] Cemiuiler: packageName com.miui.catcherpatch
[ 2023-05-29T18:53:36.053    10075: 32238: 22308 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:36.053    10075: 32238: 22308 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:48.678     1000: 23985: 23985 I/LSPosed-Bridge  ] Loading module com.gswxxn.restoresplashscreen from /data/app/~~eqju9h2py_r2opykEmWurg==/com.gswxxn.restoresplashscreen-AYi7WKJZSlVJqAHmPx5Osg==/base.apk
[ 2023-05-29T18:53:48.693     1000: 23985: 23985 I/LSPosed-Bridge  ]   Loading class com.gswxxn.restoresplashscreen.hook.HookEntry_YukiHookXposedInit
[ 2023-05-29T18:53:48.713     1000: 23985: 23985 I/LSPosed-Bridge  ] Loading module statusbar.lyric from /data/app/~~780_ytnswiLPuKyTx7O-FA==/statusbar.lyric-KsP_DuBg9vrM2eW3h1LiAQ==/base.apk
[ 2023-05-29T18:53:48.721     1000: 23985: 23985 I/LSPosed-Bridge  ]   Loading class statusbar.lyric.hook.MainHook
[ 2023-05-29T18:53:48.723     1000: 23985: 23985 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:48.739     1000: 23985: 23985 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:49.034     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: packageName com.android.systemui
[ 2023-05-29T18:53:49.035     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: Hook com.android.systemui
[ 2023-05-29T18:53:49.041     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NotificationFreeform Hook Success!
[ 2023-05-29T18:53:49.044     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: StatusBarIcon Hook Success!
[ 2023-05-29T18:53:49.053     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: StatusBarSimIcon Hook Success!
[ 2023-05-29T18:53:49.055     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: MobileNetwork Hook Success!
[ 2023-05-29T18:53:49.058     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NetworkSpeed Hook Success!
[ 2023-05-29T18:53:49.059     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NetworkSpeedUnit Hook Success!
[ 2023-05-29T18:53:49.060     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: j Success to hook postUpdateNetworkSpeedDelay method in com.android.systemui.statusbar.policy.NetworkSpeedController
[ 2023-05-29T18:53:49.060     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NetworkSpeedSpacing Hook Success!
[ 2023-05-29T18:53:49.062     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NetworkSpeedSec Hook Success!
[ 2023-05-29T18:53:49.065     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: TimeCustomization Hook Success!
[ 2023-05-29T18:53:49.079     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: j Success to hook com.android.systemui.statusbar.policy.NetworkSpeedController constructor
[ 2023-05-29T18:53:49.080     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: DisplayHardwareDetail Hook Success!
[ 2023-05-29T18:53:49.094     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: StatusBarIconPositionAdjust Hook Success!
[ 2023-05-29T18:53:49.099     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: StatusBarActions Hook Success!
[ 2023-05-29T18:53:49.107     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: AddBlurEffectToLockScreen Hook Success!
[ 2023-05-29T18:53:49.114     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: PluginHelper Hook Success!
[ 2023-05-29T18:53:49.115     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:49.115     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:50.550    10082: 24266: 24266 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:50.568    10082: 24266: 24266 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:50.812    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: packageName com.android.camera
[ 2023-05-29T18:53:50.812    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: Hook com.android.camera
[ 2023-05-29T18:53:50.818    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: Unlock60Fps Hook Success!
[ 2023-05-29T18:53:50.819    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: Unlock120Fps Hook Success!
[ 2023-05-29T18:53:50.825    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockHdr Hook Success!
[ 2023-05-29T18:53:50.829    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockAiEnhance Hook Success!
[ 2023-05-29T18:53:50.830    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockAudioZoom Hook Success!
[ 2023-05-29T18:53:50.831    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockCvlens Hook Failed!
[ 2023-05-29T18:53:50.831    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockCvlens FailedInfo：java.lang.NoSuchMethodError: com.android.camera.CameraSettings#getCvLensVersion()#exact
[ 2023-05-29T18:53:50.833    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockNewBeauty Hook Success!
[ 2023-05-29T18:53:50.833    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockTrackFeature Hook Failed!
[ 2023-05-29T18:53:50.833    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockTrackFeature FailedInfo：java.lang.NoSuchMethodError: com.android.camera2.CameraCapabilities#isSupportTrackFeatureEnable()#exact
[ 2023-05-29T18:53:50.837    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: EnableLabOptions Hook Success!
[ 2023-05-29T18:53:50.839    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: UnlockTrackEyes Hook Success!
[ 2023-05-29T18:53:50.840    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:50.840    10082: 24266: 24266 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:51.264    10164: 24442: 24442 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:51.291    10164: 24442: 24442 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:51.446     1000: 24481: 24481 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:51.466     1000: 24481: 24481 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:51.663    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: packageName com.milink.service
[ 2023-05-29T18:53:51.663    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: Hook com.milink.service
[ 2023-05-29T18:53:51.668    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: find com.miui.circulate.world.auth.AuthUtil is Null
[ 2023-05-29T18:53:51.668    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: Erro: [java.lang.ClassNotFoundException: com.miui.circulate.world.auth.AuthUtil]
[ 2023-05-29T18:53:51.669    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: find com.miui.circulate.world.utils.GetKeyUtil is Null
[ 2023-05-29T18:53:51.669    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: Erro: [java.lang.ClassNotFoundException: com.miui.circulate.world.utils.GetKeyUtil]
[ 2023-05-29T18:53:51.669    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: UnlockMiShare Hook Success!
[ 2023-05-29T18:53:51.670    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:51.670    10164: 24442: 24442 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:51.796     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: DisplayHardwareDetail fontsize = 6.5
[ 2023-05-29T18:53:51.797     1000: 23985: 23985 I/LSPosed-Bridge  ] Cemiuiler: DisplayHardwareDetail fontsize = 6.5
[ 2023-05-29T18:53:52.112     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: packageName com.android.settings
[ 2023-05-29T18:53:52.112     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: Hook com.android.settings
[ 2023-05-29T18:53:52.169     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: VoipAssistantController Hook Success!
[ 2023-05-29T18:53:52.202     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: PermissionTopOfApp Hook Success!
[ 2023-05-29T18:53:52.203     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: QuickInstallPermission Hook Success!
[ 2023-05-29T18:53:52.205     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:52.205     1000: 24481: 24481 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:53:53.034    10265: 24782: 24782 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:53:53.053    10265: 24782: 24782 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:53:53.397    10265: 24782: 24782 I/LSPosed-Bridge  ] Cemiuiler: packageName com.miui.weather2
[ 2023-05-29T18:53:53.397    10265: 24782: 24782 I/LSPosed-Bridge  ] Cemiuiler: Hook com.miui.weather2
[ 2023-05-29T18:53:53.398    10265: 24782: 24782 I/LSPosed-Bridge  ] Cemiuiler: SetDeviceLevel Start to hook package com.miui.weather2
[ 2023-05-29T18:53:53.404    10265: 24782: 24782 I/LSPosed-Bridge  ] Cemiuiler: SetDeviceLevel Hook Success!
[ 2023-05-29T18:53:53.405    10265: 24782: 24782 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:53:53.405    10265: 24782: 24782 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService
[ 2023-05-29T18:54:07.651    10089: 26540: 26540 I/LSPosed-Bridge  ] Loading module com.sevtinge.cemiuiler from /data/app/~~MOBCcMd9sOA7ilzBfT_MTQ==/com.sevtinge.cemiuiler-TInB3rHsa6sQqK-5KFyUHw==/base.apk
[ 2023-05-29T18:54:07.685    10089: 26540: 26540 I/LSPosed-Bridge  ]   Loading class com.sevtinge.cemiuiler.XposedInit
[ 2023-05-29T18:54:07.903    10089: 26540: 26540 I/LSPosed-Bridge  ] Cemiuiler: packageName com.android.externalstorage
[ 2023-05-29T18:54:07.903    10089: 26540: 26540 I/LSPosed-Bridge  ] Cemiuiler: Hook com.android.externalstorage
[ 2023-05-29T18:54:07.908    10089: 26540: 26540 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest Hook Failed!
[ 2023-05-29T18:54:07.908    10089: 26540: 26540 I/LSPosed-Bridge  ] Cemiuiler: NoAccessDeviceLogsRequest FailedInfo：de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.logcat.LogcatManagerService

### 复现步骤

```bash
网速指示器，开启自定义，显示上下行，双排显示上下行
出现问题
```

### 机型

mi11

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.0.115_20230528

**Comment by mu7220** [comment]
网速字体大小调了没，还有你上传的图片有问题，重新上传一份
