### ISSUE TITLE
🔌 [移植] <请求移植chimi的网速功能>

### ISSUE THREAD

**Issue by soulpursuit** [Cemiuiler-Development-Team/Cemiuiler#159]
### 仓库地址

https://github.com/yonghen/chimi-

### 移植内容

请求移植chimi的网速功能，用遍了市面的所有状态栏插件，只有chimi的网速显示，上下行之间没有任何的间隙，其他的模块显示的网速功能，上行与下载的都显得非常单独

### 相关描述&截图

![Screenshot_2023-06-05-15-31-45-114_mark via](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/48674277/10c2c248-135f-48e6-a786-e6337bff7c46)

**Comment by mu7220** [comment]
它没开源，移植不了
