### ISSUE TITLE
🐛 [BUG] 重启后需等待应用响应请稍后再试

### ISSUE THREAD

**Issue by wangyuan0217** [Cemiuiler-Development-Team/Cemiuiler#165]
### 问题描述

不确定是不是这个模块导致的；
2天前装了这个模块，今天下午正常使用手机，时间长了稍微有点热和卡，想着重启下，结果重启后进入到桌面点击任一个app图标都提示   “重启后需等待应用响应请稍后再试”， 只有系统设置的图标能点进去(里面的很多功能也会闪退)；
手机是解锁装了magisk和lsp的一些框架的日常一直使用都没问题的，所以不确定是不是装了这个软件导致的；

### 模块日志

....

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

小米12sp

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.1.116_20230602

**Comment by mu7220** [comment]
请关闭 开机免输入密码 功能，上面提示写得很清楚了

**Comment by wangyuan0217** [comment]
感谢！  不过幸好装了音量键救砖的模块，禁用了magisk模块进来了
