### ISSUE TITLE
🐛 [BUG] 不要 spam Xposed 日志

### ISSUE THREAD

**Issue by ex-hentai** [Cemiuiler-Development-Team/Cemiuiler#166]
### 问题描述

XposedBridge.log 应该仅用于错误日志

### 模块日志

没有

### 复现步骤

```bash
没有
```

### 问题截图

```Markdown
没有
```

### 机型

没有

### MIUI版本

其它

### Cemiuiler版本号

1.1.116

**Comment by mu7220** [comment]
请让 @Sevtinge 背锅，能不输出的东西已经优化过了

剩下的你把禁用详细日志开开就只剩下核心破解及模块必要 error 日志

**Comment by mu7220** [comment]
> > 请让 @Sevtinge 背锅，能不输出的东西已经优化过了
> > 
> > 剩下的你把禁用详细日志开开就只剩下核心破解及模块必要 error 日志
> 
> 日志里成吨 hook success

![Screenshot_2023-06-11-16-18-12-950_com.sevtinge.cemiuiler-edit.jpg](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/80700814/b9e93359-2dd1-4050-b621-20a900003c39)

请，我不想重复第二次（
