### ISSUE TITLE
🐛 [BUG] <问题标题>

### ISSUE THREAD

**Issue by Cyugin** [Cemiuiler-Development-Team/Cemiuiler#177]
### 问题描述

主页搜索栏位无法点击，无法进行搜索

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

小米

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.1.116_20230602

**Comment by mu7220** [comment]
不是bug，没做完呢，只是个UI而已
