### ISSUE TITLE
💡 [需求] <MIUI14解锁PPTP设置>

### ISSUE THREAD

**Issue by LiuZhipeng99** [Cemiuiler-Development-Team/Cemiuiler#182]
### 需求内容

从MIUI13升级到14发现不能添加PPTP了，但以前设置PPTP连接还能选择旧协议

### 实现思路&截图

![cb88ee667199ebd10f00eececaf04a6](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/44400198/a529218e-4868-47f0-bdd0-dd9c8edfd533)

### 简单例子

内网还在使用老旧的PPTP

**Comment by mu7220** [comment]
这个东西解锁了也没用了，详见
https://www.coolapk.com/feed/35525705
