### ISSUE TITLE
💡 [需求] <堆叠桌面>

### ISSUE THREAD

**Issue by darescloud** [Cemiuiler-Development-Team/Cemiuiler#189]
### 需求内容

添加Xposeded大佬的堆叠后台

### 实现思路&截图

他好像是开源的，把后台列表的第二种改成堆叠效果

### 简单例子

像iOS那样的堆叠后台

**Comment by TacKana** [comment]
那你为什么不直接安装别人的模块？

**Comment by darescloud** [comment]
> 那你为什么不直接安装别人的模块？

？？西米露为什么要做出来？不就是为了一个整合吗？？你为什么不说让我买个苹果呢？

**Comment by TacKana** [comment]
目前我看到这个插件的功能都是把阉割的东西拿回来的，可是你这个堆叠桌面MIUI你压根就没有吧，真的，这个需求还不如自己安装模块

**Comment by darescloud** [comment]
> 目前我看到这个插件的功能都是把阉割的东西拿回来的，可是你这个堆叠桌面MIUI你压根就没有吧，真的，这个需求还不如自己安装模块

所以我为什么放在需求板块呢？哥们你闲着的吧

**Comment by darescloud** [comment]
> 目前我看到这个插件的功能都是把阉割的东西拿回来的，可是你这个堆叠桌面MIUI你压根就没有吧，真的，这个需求还不如自己安装模块

目前没有模块啊，只有他的修改版桌面

**Comment by mu7220** [comment]
不打算做，模块实现难度过大
