### ISSUE TITLE
解析包出现问题🐛 [BUG] <问题标题>

### ISSUE THREAD

**Issue by wgql1023** [Cemiuiler-Development-Team/Cemiuiler#193]
### 问题描述

米9 12.5
面具 太极

### 模块日志

面具 太极

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

9

### MIUI版本

MIUI13 Android 12

### Cemiuiler版本号

最新

**Comment by mu7220** [comment]
没看懂，请具体描述下

**Comment by wgql1023** [comment]
王刚|网站建设、企业运营推广www.whabm.com | ***@***.***

**Comment by wgql1023** [comment]
王刚|网站建设、企业运营推广www.whabm.com | ***@***.***
