### ISSUE TITLE
💡 [需求] 请求添加状态栏时钟居右侧

### ISSUE THREAD

**Issue by vay1314** [Cemiuiler-Development-Team/Cemiuiler#197]
### 需求内容

请求添加时钟位居右侧的功能

### 实现思路&截图

![Screenshot_2023-06-30-16-16-43-399_com miui gallery-edit](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/22141920/aeed79b3-017f-41dc-ac13-5e78622b073f)

### 简单例子

请求添加时钟位居右侧的功能

**Comment by mu7220** [comment]
最新版（1.1.119）有的，lsp仓库更新一下就是……

**Comment by vay1314** [comment]
> 最新版本（1.1.119）有的，lsp仓库更新一下就是……

我现在是1.2.120没有啊，lsp仓库是1.118，我120我搜索设置也没这项。

**Comment by mu7220** [comment]
> > 最新版本（1.1.119）有的，lsp仓库更新一下就是……
> 
> 我现在是1.2.120没有啊，lsp仓库是1.118，我120我搜索设置也没这项。

在 系统界面-状态栏-布局-布局模式 里

**Comment by vay1314** [comment]
> > > 最新版本（1.1.119）有的，lsp仓库更新一下就是……
> > 
> > 
> > 我现在是1.2.120没有啊，lsp仓库是1.118，我120我搜索设置也没这项。
> 
> 在 系统界面-状态栏-布局-布局模式 里

好的，谢谢。搜索设置没有，以为就没这个功能了
