### ISSUE TITLE
💡 [需求] <请更换，关于 MIUI传送门>

### ISSUE THREAD

**Issue by razilong** [Cemiuiler-Development-Team/Cemiuiler#202]
### 需求内容

请优先使用 [传送门增强](https://github.com/Xposed-Modules-Repo/io.github.yangyiyu08.taplusext) 
而非 [PortalHook](https://github.com/Haocen2004/PortalHook) 
前者包含了后者并支持更多功能，仍在更新，且识别算法优化得不错，后者PortalHook已停更1年

### 简单例子

![Screenshot_2023-07-06-19-19-10-234_com github android](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/97635957/5f3b9b3d-6028-4549-9838-4bd49a1c066f)
![Screenshot_2023-07-06-19-35-52-514-edit_com miui contentextension](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/97635957/b3119869-fb40-4529-91ca-5aebfbbf873b)

**Comment by mu7220** [comment]
cemiuiler 目前整合的是已开源的代码，而传送门增强并未开源代码，所以没有使用

而 cemiuiler 目前能做的，也就在基于已开源的项目中维护和优化
