### ISSUE TITLE
🔌 [移植] 米客 音乐可视化

### ISSUE THREAD

**Issue by 2053628642** [Cemiuiler-Development-Team/Cemiuiler#203]
### 仓库地址

https://github.com/monwf/customiuizer

### 移植内容

移植米客的音乐可视化功能，并且让此功能不再局限于通知栏抽屉

### 相关描述&截图

![Screenshot_2023-02-19-01-19-28-101_name monwf customiuizer](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/93074770/43a3c5bf-2b6a-489e-91a4-fca15cb9a401)

**Comment by mu7220** [comment]
不打算做，这个功能会导致系统性能受到影响
