### ISSUE TITLE
💡 [需求] <标题>希望可以在<联网控制>中加入对系统应用的WLAN控制

### ISSUE THREAD

**Issue by Mrqqeat** [Cemiuiler-Development-Team/Cemiuiler#212]
### 需求内容

MIUI14系统的<联网控制>功能中只能对系统应用禁用移动网络，无法禁用WLAN。
希望可以加入此功能来让系统应用不能使用WLAN联网。

### 简单例子

MIUI14系统的<联网控制>功能中只能对系统应用禁用移动网络，无法禁用WLAN。
希望可以加入此功能来让系统应用不能使用WLAN联网。

**Comment by mu7220** [comment]
手机管家-全限制 那个就是

**Comment by Mrqqeat** [comment]
> 手机管家-全限制 那个就是

好的感谢，我没认真看emmm
