### ISSUE TITLE
网速悬浮

### ISSUE THREAD

**Issue by zhanghaoyu0** [Cemiuiler-Development-Team/Cemiuiler#224]
### 需求内容

状态栏网速改为悬浮网速  降低状态的使用空间

### 简单例子

为状态栏网速改为悬浮显示以便增加状态的显示空间

**Comment by mu7220** [comment]
经考虑，不打算做

**Comment by zhanghaoyu0** [comment]
好吧  没看到回复信息  又反馈了一条同款建议  抱歉
