### ISSUE TITLE
🐛 [BUG] 使用修改的堆叠后台桌面时小部件移动到负一屏和解锁小部件大小功能失效。

### ISSUE THREAD

**Issue by nljxlove** [Cemiuiler-Development-Team/Cemiuiler#227]
### 问题描述

使用的是@TAT趙的最新修改版的堆叠桌面，实测小部件移动到负一屏和解锁小部件大小功能失效。

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

小米13

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.2.122_20230716_beta

**Comment by mu7220** [comment]
修改版桌面模块不会额外提供支持，你到哪个模块说适配也是这样
