### ISSUE TITLE
🔌 [移植] 单击磁贴开关后自动收起

### ISSUE THREAD

**Issue by X1zzzw** [Cemiuiler-Development-Team/Cemiuiler#229]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

米客—>控制中心—>单击开关后自动收起
小建议：如果只是下面小磁贴有此功能感觉会更好些

### 相关描述&截图

![微信图片编辑_20230724152257](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/65091392/1f8a7b0a-38b9-4dd9-a69d-ea26e4623b75)

**Comment by HChenX** [comment]
已经添加🥳
