### ISSUE TITLE
🐛 [BUG] 应用包管理组件内的功能失效

### ISSUE THREAD

**Issue by Nep-Timeline** [Cemiuiler-Development-Team/Cemiuiler#233]
### 问题描述

应用包管理组件功能无效

### 模块日志

（LSPosed保存下来的日志都是0B打不开的 所以直接发截图了）
![Screenshot_2023-07-27-19-13-46-545_com android sh](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/53483352/0d94a63e-cae6-4ff1-bc72-8c08441d7624)
![Screenshot_2023-07-27-19-13-37-853_com android sh](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/53483352/e22442ac-a0c7-48d9-893b-ebcecd7d8fc6)

### 复现步骤

应用包管理组件版本: 5.1.5.3-20230725

### 机型

Xiaomi 13

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.2.122_20230727

**Comment by mu7220** [comment]
剩下坏掉的功能明天修复，先标记已完成了

**Comment by Nep-Timeline** [comment]
> 剩下坏掉的功能明天修复，先标记已完成了

好的谢谢
