### ISSUE TITLE
添加搜索功能💡 [需求] <标题>

### ISSUE THREAD

**Issue by Heaven7528** [Cemiuiler-Development-Team/Cemiuiler#34]
### 需求内容

小功能太多了，有些东西找的时候找不到，希望可以添加类似米客的搜索功能，便于查找

### 简单例子

添加功能搜索

**Comment by P3R5T7U9** [comment]
和这条issue的层主一样，同求Sevtinge大佬增加此xp模块的“搜索”功能

**Comment by Heaven7528** [comment]
好耶












何旭升
***@***.***


---原始邮件---
发件人: "Neko ***@***.***&gt;
发送时间: 2023年6月19日(周一) 凌晨2:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cemiuiler-Development-Team/Cemiuiler] 添加搜索功能💡 [需求] <标题&gt; (Issue #34)




 
Closed #34 as completed.
