### ISSUE TITLE
💡 [需求] 系统桌面-手势加入更多功能

### ISSUE THREAD

**Issue by 1175592624** [Cemiuiler-Development-Team/Cemiuiler#49]
### 需求内容

希望在桌面系统-手势中加入更多选项，更加快捷地在桌面控制或打开软件

### 实现思路&截图

![Screenshot_2023-05-03-14-02-57-889_name monwf customiuizer](https://user-images.githubusercontent.com/67873712/235842438-c5437290-2ba7-4a6a-81e5-653333eba2d0.jpg)
![Screenshot_2023-05-03-14-03-03-828_name monwf customiuizer](https://user-images.githubusercontent.com/67873712/235842440-f8a2aa21-06fc-42d5-900f-fc920feea73a.jpg)
![Screenshot_2023-05-03-14-03-53-065_com sevtinge cemiuiler](https://user-images.githubusercontent.com/67873712/235842452-0a95b121-2ded-4b71-b936-42f03bf595d5.jpg)

### 简单例子

希望在桌面系统-手势中加入更多选项，例如：单手模式、控制中心、也可以支持自定义化的快捷方式

**Comment by mu7220** [comment]
有考虑
这个截图的应用是哪个模块，我试着往cemiuiler补全一下

**Comment by 1175592624** [comment]
米客[https://github.com/MonwF/customiuizer/tree/main](url)

**Comment by mu7220** [comment]
已添加部分功能，其他等待后续评估（有一些已经pass掉了）
