### ISSUE TITLE
🐛 [BUG] 控制中心状态栏温度大小异常

### ISSUE THREAD

**Issue by Yan546** [Cemiuiler-Development-Team/Cemiuiler#62]
### 问题描述

切换分辨率后控制中心状态栏温度显示变大，只能重启系统界面解决

### 模块日志

LSPosed_2023-05-06T21_03_17.221663.zip
https://wwyg.lanzouo.com/ix3gt0uulr8h

### 复现步骤

```bash
切换1080P/2K分辨率都会这样
```

### 问题截图

```Markdown
https://wwyg.lanzouo.com/igvlO0uuluif
```

### 机型

Redmi K50 Pro

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.0.103_20230504(103)

**Comment by mu7220** [comment]
暂时性无解，米客也这样，除非MIUI什么时候改切换分辨率逻辑
