### ISSUE TITLE
💡 [需求] 可选移除电池图标

### ISSUE THREAD

**Issue by oxy2ray** [Cemiuiler-Development-Team/Cemiuiler#88]
### 需求内容

目前 Cemiuiler 只能移除电量的百分号，不能移除电池图标。其它同类插件可做到这一点。

### 实现思路&截图

实现效果:
![Screenshot_2023-05-16-03-21-20-431_com android chrome-edit](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/67837739/b4e29387-83b1-4910-a670-b941a0c026ed)

### 简单例子

WooBox > Hide Icon > 隐藏电池图标

**Comment by mu7220** [comment]
1.0.107 已经完成了，使用的是woobox逻辑
